import { defineField, defineType } from 'sanity';

export default defineType({
  name: 'order',
  title: 'Orders',
  type: 'document',
  fieldsets: [
    { name: 'customerInfo', title: 'Customer Info', options: { collapsible: true, collapsed: false } },
    { name: 'orderDetails', title: 'Order Details', options: { collapsible: true, collapsed: false } },
    { name: 'payment', title: 'Pricing & Payment', options: { collapsible: true, collapsed: false } },
    { name: 'status', title: 'Status Tracking', options: { collapsible: true, collapsed: false } },
    { name: 'admin', title: 'Admin Controls', options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: 'userEmail',
      title: 'User Email (Owner)',
      type: 'string',
      fieldset: 'customerInfo',
    }),
    defineField({
      name: 'assignedArtist',
      title: 'Assigned Artist',
      type: 'reference',
      to: [{ type: 'userProfile' }],
      options: {
        filter: 'role == "artist"',
      },
      fieldset: 'admin',
    }),
    defineField({
      name: 'orderId',
      title: 'Order ID',
      type: 'string',
      description: 'Unique identifier generated upon submission.',
      validation: (Rule) => Rule.required().error('Order ID is critical for tracking.'),
      fieldset: 'customerInfo',
      readOnly: true, // Should typically be generated by frontend API
    }),
    defineField({
      name: 'customerName',
      title: 'Customer Name',
      type: 'string',
      validation: (Rule) => Rule.required().error('Customer name is required.'),
      fieldset: 'customerInfo',
    }),
    defineField({
      name: 'email',
      title: 'Email Address',
      type: 'string',
      validation: (Rule) => 
        Rule.required()
          .regex(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/, {
            name: 'email', 
            invert: false,
          })
          .error('A valid email address is required.'),
      fieldset: 'customerInfo',
    }),
    defineField({
      name: 'address',
      title: 'Shipping Address',
      type: 'text',
      rows: 3,
      fieldset: 'customerInfo',
    }),
    defineField({
      name: 'pincode',
      title: 'Pin Code',
      type: 'string',
      validation: (Rule) => Rule.regex(/^\d{6}$/).error('Invalid 6-digit pin code.'),
      fieldset: 'customerInfo',
    }),
    defineField({
      name: 'phone',
      title: 'Phone Number',
      type: 'string',
      validation: (Rule) => Rule.required().min(10).error('Phone number is required starting with area code.'),
      fieldset: 'customerInfo',
    }),

    defineField({
      name: 'artworkType',
      title: 'Artwork Type',
      type: 'string',
      options: {
        list: [
          { title: 'Sketch (Pencil/Charcoal)', value: 'sketch' },
          { title: 'Painting (Acrylic/Watercolor)', value: 'painting' },
          { title: 'Digital Art', value: 'digital' },
        ],
      },
      validation: (Rule) => Rule.required().error('Artwork type must be selected.'),
      fieldset: 'orderDetails',
    }),
    defineField({
      name: 'description',
      title: 'Custom Requirements',
      type: 'text',
      rows: 4,
      fieldset: 'orderDetails',
    }),
    defineField({
      name: 'referenceImage',
      title: 'Reference Image',
      type: 'url',
      description: 'Image provided by the customer for reference.',
      fieldset: 'orderDetails',
    }),
    defineField({
      name: 'artworkId',
      title: 'Linked Artwork',
      type: 'reference',
      to: [{ type: 'artwork' }],
      description: 'Reference to an existing gallery piece if this is a direct purchase.',
      fieldset: 'orderDetails',
    }),

    defineField({
      name: 'price',
      title: 'Quoted Price (₹)',
      type: 'number',
      validation: (Rule) => Rule.required().positive().error('Price must be greater than 0.'),
      fieldset: 'payment',
    }),
    defineField({
      name: 'paymentStatus',
      title: 'Payment Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending Verification', value: 'pending' },
          { title: 'Paid / Confirmed', value: 'paid' },
        ],
      },
      initialValue: 'pending',
      validation: (Rule) => Rule.required(),
      fieldset: 'payment',
    }),
    defineField({
      name: 'paymentProof',
      title: 'Payment Proof (Screenshot)',
      type: 'url',
      description: 'Screenshot of the UPI transaction (optional).',
      fieldset: 'payment',
    }),

    defineField({
      name: 'orderStatus',
      title: 'Fulfillment Status',
      type: 'string',
      options: {
        list: [
          { title: 'Pending / Unstarted', value: 'pending' },
          { title: 'Artist Assigned', value: 'assigned' },
          { title: 'Work In Progress', value: 'progress' },
          { title: 'Review Phase', value: 'review' },
          { title: 'Completed & Delivered', value: 'completed' },
        ],
      },
      initialValue: 'pending',
      validation: (Rule) => Rule.required(),
      fieldset: 'status',
    }),
    defineField({
      name: 'createdAt',
      title: 'Submitted At',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      fieldset: 'status',
      readOnly: true,
    }),
    defineField({
      name: 'updatedAt',
      title: 'Last Updated At',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      fieldset: 'status',
    }),

    defineField({
      name: 'adminNotes',
      title: 'Admin / Artist Notes',
      type: 'text',
      rows: 3,
      description: 'Private notes only visible to you. E.g. "Customer requested pure black ink".',
      fieldset: 'admin',
    }),

    // ── Cart Order Fields (optional — only populated for multi-item cart purchases) ──
    defineField({
      name: 'cartItems',
      title: 'Cart Items',
      type: 'array',
      description: 'Populated for multi-artwork cart purchases. Empty for single commissions.',
      of: [{
        type: 'object',
        fields: [
          { name: 'artworkId', title: 'Artwork ID', type: 'string' },
          { name: 'title', title: 'Title', type: 'string' },
          { name: 'price', title: 'Price (₹)', type: 'number' },
          { name: 'imageUrl', title: 'Image URL', type: 'url' },
        ],
      }],
      fieldset: 'orderDetails',
    }),
    defineField({
      name: 'totalAmount',
      title: 'Cart Total Amount (₹)',
      type: 'number',
      description: 'Final amount after discount. Used for cart orders.',
      fieldset: 'payment',
    }),
    defineField({
      name: 'couponCode',
      title: 'Coupon Code Applied',
      type: 'string',
      fieldset: 'payment',
    }),
    defineField({
      name: 'discountAmount',
      title: 'Discount Applied (₹)',
      type: 'number',
      fieldset: 'payment',
    }),
    defineField({
      name: 'orderType',
      title: 'Order Type',
      type: 'string',
      options: {
        list: [
          { title: 'Commission', value: 'commission' },
          { title: 'Cart Purchase', value: 'cart' },
          { title: 'Direct Buy', value: 'direct' },
        ],
      },
      initialValue: 'commission',
      fieldset: 'orderDetails',
    }),
    defineField({
      name: 'artworkUrl',
      title: 'Final Artwork Image (URL)',
      type: 'string',
      description: 'The final fulfilled artwork URL from Cloudinary.',
      fieldset: 'status',
    }),
    
  ],
  preview: {
    select: {
      title: 'customerName',
      subtitle: 'orderId',
      status: 'orderStatus',
    },
    prepare({ title, subtitle, status }) {
      const statusMap: Record<string, string> = {
        pending: '🟡 Pending',
        in_progress: '🔵 In Progress',
        completed: '🟢 Completed',
      };
      return {
        title: `${title} - ID: ${subtitle}`,
        subtitle: `Status: ${statusMap[status as string] || 'Unknown Phase'}`,
      };
    },
  },
});

